#!/usr/bin/env perl
    
use strict; 
use warnings;
    
use Getopt::Long::Descriptive;
use IO::Prompter;
    
my ($option, $usage) = describe_options(
    'usage: git ribbon %o',
    ['save|s=i'       => 'Save your place at origin/branch'],
    ['help|h'         => 'Show this message'],
);  
    
die($usage) if $option->{help};

my @logs = `git log --pretty=format:'git difftool -r %p -r %h --no-prompt %n%C(bold white)%an %cr %h%n%s%Creset' --name-only --no-merges --reverse --topo-order _ribbon..origin/master`;

my $i = 0;
while ($i < $#logs) {
    my $cmd = $logs[$i];
    $i++;

    while ($logs[$i] !~ /^git difftool -r /) {
        print $logs[$i];
        $i++;
        last if $i >= $#logs;
    }

    my $answer = prompt "press 's' to skip", -echo => "", -single;

    unless ($answer eq 's') {
        my $pid = fork();
        if (!$pid) { # child
            exec($cmd);
        }
        waitpid $pid, 0;
    }
    
    print "\n";
}

END { print "\n" }
